--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2020/1/13 9:33:37
-- Server version: 8.0.15
-- Client version: 4.1
--


SET NAMES '';

INSERT INTO ebook.cart(user_id, book_id, number) VALUES
(1, 4, 1),
(3, 3, 2),
(3, 5, 1),
(3, 11, 1),
(3, 13, 1),
(34, 13, 19);