--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2020/1/13 9:33:40
-- Server version: 8.0.15
-- Client version: 4.1
--


SET NAMES '';

INSERT INTO ebook.users(user_id, account, password, mailbox, status, ismanager) VALUES
(1, 'root', '12345', '21512@sjtu.edu.cn', 'valid', 1),
(2, 'user1', 'user1', '111111@sjtu.edu.cn', 'valid', 0),
(3, 'user2', 'user2', '222222@sjtu.edu.cn', 'valid', 0),
(4, 'user3', 'user3', '333333@sjtu.edu.cn', 'valid', 0),
(29, 'guo', 'zhi', '234553@sjtu.edu.cn', 'valid', 0),
(30, 'user7', 'user7', '0000@qq.com', 'forbid', 0),
(31, 'user6', 'user6', '0000@qq.com', 'forbid', 0),
(32, 'user5', 'user5', '0000@qq.com', 'valid', 0),
(33, 'wen', 'qian', '520@you.com', 'forbid', 0),
(34, 'zhaoxuyang', '123456qwerty', 'qwert@sjtu.edu.cn', 'valid', 0),
(51, 'user18', 'user10', '0000@qq.com', 'valid', 0),
(52, 'user21', '12345', '234553@sjtu.edu.cn', 'valid', 0),
(53, 'wenxuanda', '1234567', '0000@qq.com', 'forbid', 0);